title: Leopard's blog about Data
author: Leopard
email: xinsheng.lian@qq.com
description: > # this means to ignore newlines until "baseurl:"
This is my first blog in github.

# social links
twitter_username: NA
github_username:  leopardlian

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
